// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// friedman_test_matrix
List friedman_test_matrix(const NumericMatrix& data);
RcppExport SEXP _nullis_friedman_test_matrix(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(friedman_test_matrix(data));
    return rcpp_result_gen;
END_RCPP
}
// friedman_test_group
List friedman_test_group(const NumericVector& x, const CharacterVector& treatment, const CharacterVector& block);
RcppExport SEXP _nullis_friedman_test_group(SEXP xSEXP, SEXP treatmentSEXP, SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type treatment(treatmentSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(friedman_test_group(x, treatment, block));
    return rcpp_result_gen;
END_RCPP
}
// jonckheere_terpstra_test
List jonckheere_terpstra_test(const NumericVector& values, const IntegerVector& groups, std::string alternative, bool approximate);
RcppExport SEXP _nullis_jonckheere_terpstra_test(SEXP valuesSEXP, SEXP groupsSEXP, SEXP alternativeSEXP, SEXP approximateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< bool >::type approximate(approximateSEXP);
    rcpp_result_gen = Rcpp::wrap(jonckheere_terpstra_test(values, groups, alternative, approximate));
    return rcpp_result_gen;
END_RCPP
}
// jonckheere_terpstra_test_groups
List jonckheere_terpstra_test_groups(const List& groups, std::string alternative, bool approximate);
RcppExport SEXP _nullis_jonckheere_terpstra_test_groups(SEXP groupsSEXP, SEXP alternativeSEXP, SEXP approximateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< bool >::type approximate(approximateSEXP);
    rcpp_result_gen = Rcpp::wrap(jonckheere_terpstra_test_groups(groups, alternative, approximate));
    return rcpp_result_gen;
END_RCPP
}
// kruskal_wallis_cpp
List kruskal_wallis_cpp(const List& groups);
RcppExport SEXP _nullis_kruskal_wallis_cpp(SEXP groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type groups(groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(kruskal_wallis_cpp(groups));
    return rcpp_result_gen;
END_RCPP
}
// kruskal_wallis_group
List kruskal_wallis_group(const NumericVector& x, const CharacterVector& g);
RcppExport SEXP _nullis_kruskal_wallis_group(SEXP xSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(kruskal_wallis_group(x, g));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nullis_friedman_test_matrix", (DL_FUNC) &_nullis_friedman_test_matrix, 1},
    {"_nullis_friedman_test_group", (DL_FUNC) &_nullis_friedman_test_group, 3},
    {"_nullis_jonckheere_terpstra_test", (DL_FUNC) &_nullis_jonckheere_terpstra_test, 4},
    {"_nullis_jonckheere_terpstra_test_groups", (DL_FUNC) &_nullis_jonckheere_terpstra_test_groups, 3},
    {"_nullis_kruskal_wallis_cpp", (DL_FUNC) &_nullis_kruskal_wallis_cpp, 1},
    {"_nullis_kruskal_wallis_group", (DL_FUNC) &_nullis_kruskal_wallis_group, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nullis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
