# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

friedman_test_cpp <- function(blocks) {
    .Call(`_nullis_friedman_test_cpp`, blocks)
}

friedman_test_matrix <- function(data) {
    .Call(`_nullis_friedman_test_matrix`, data)
}

friedman_test_group <- function(x, treatment, block) {
    .Call(`_nullis_friedman_test_group`, x, treatment, block)
}

jonckheere_terpstra_test <- function(values, groups, alternative = "two.sided", approximate = FALSE) {
    .Call(`_nullis_jonckheere_terpstra_test`, values, groups, alternative, approximate)
}

jonckheere_terpstra_test_groups <- function(groups, alternative = "two.sided", approximate = FALSE) {
    .Call(`_nullis_jonckheere_terpstra_test_groups`, groups, alternative, approximate)
}

kruskal_wallis_cpp <- function(groups) {
    .Call(`_nullis_kruskal_wallis_cpp`, groups)
}

kruskal_wallis_group <- function(x, g) {
    .Call(`_nullis_kruskal_wallis_group`, x, g)
}

